services:
  - type: web
    name: boss-shop
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python production_start.py
    envVars:
      - key: PORT
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "boss_shopp.settings"
    autoDeploy: true